import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "react-hot-toast";
import AosProvider from "@/Provider/AosProvider/AosProvider";
import QueryProvider from "@/Provider/QueryProvider/QueryProvider";
import ReduxProvider from "@/Provider/ReduxProvider/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Miskstoreg",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <QueryProvider>
          <ReduxProvider>
            <AosProvider>{children}</AosProvider>
            <Toaster />
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
